# Generated by Django 5.2.1 on 2026-05-29 11:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='source',
            field=models.CharField(choices=[('ui', 'UI'), ('import', 'Import'), ('backup', 'Backup'), ('restore', 'Restore'), ('script', 'Script'), ('scheduler', 'Scheduler')], default='ui', max_length=20),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Создание'), ('update', 'Изменение'), ('delete', 'Удаление'), ('restore', 'Восстановление'), ('upload_document', 'Загрузка документа'), ('system_mode_change', 'Смена режима системы'), ('backup_queued', 'Backup поставлен в очередь'), ('backup_started', 'Backup запущен'), ('backup_success', 'Backup выполнен'), ('backup_error', 'Ошибка backup'), ('restore_queued', 'Restore поставлен в очередь'), ('restore_started', 'Restore запущен'), ('restore_success', 'Restore выполнен'), ('restore_error', 'Ошибка restore'), ('operation_recovered', 'Сброс системной операции'), ('backup_schedule_updated', 'Расписание backup изменено')], max_length=50),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='entity_type',
            field=models.CharField(choices=[('auto_shipment', 'Автоотгрузка'), ('rail_shipment', 'ЖД-отгрузка'), ('document', 'Документ'), ('user', 'Пользователь'), ('system', 'Система'), ('backup', 'Backup'), ('restore', 'Restore')], max_length=50),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['source'], name='idx_audit_source'),
        ),
    ]
