# Generated by Django 5.2.1 on 2026-06-11 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0004_alter_auditlog_action_alter_auditlog_entity_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Создание'), ('update', 'Изменение'), ('delete', 'Удаление'), ('restore', 'Восстановление'), ('upload_document', 'Загрузка документа'), ('edit_document', 'Изменение документа'), ('delete_document', 'Удаление документа'), ('system_mode_change', 'Смена режима системы'), ('backup_queued', 'Backup поставлен в очередь'), ('backup_started', 'Backup запущен'), ('backup_success', 'Backup выполнен'), ('backup_error', 'Ошибка backup'), ('restore_queued', 'Restore поставлен в очередь'), ('restore_started', 'Restore запущен'), ('restore_success', 'Restore выполнен'), ('restore_error', 'Ошибка restore'), ('operation_recovered', 'Сброс системной операции'), ('backup_schedule_updated', 'Расписание backup изменено'), ('catalog_rename', 'Переименование справочника'), ('auth_lockout', 'Блокировка входа (axes)')], max_length=50),
        ),
    ]
