# Generated by Django 5.2.1 on 2026-05-14 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutoBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'База авто',
                'verbose_name_plural': 'Базы авто',
                'db_table': 'catalog_auto_bases',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AutoCoalGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Марка угля (авто)',
                'verbose_name_plural': 'Марки угля (авто)',
                'db_table': 'catalog_auto_coal_grades',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RailCoalGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Марка угля (ЖД)',
                'verbose_name_plural': 'Марки угля (ЖД)',
                'db_table': 'catalog_rail_coal_grades',
                'ordering': ['name'],
            },
        ),
    ]
