# Generated by Django 5.2.1 on 2026-05-15 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catalog_type', models.CharField(choices=[('auto_coal_grade', 'Марка угля (авто)'), ('auto_base', 'База отгрузки (авто)'), ('rail_coal_grade', 'Марка угля (ЖД)')], max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'catalog_values',
                'ordering': ['catalog_type', 'name'],
                'indexes': [models.Index(fields=['catalog_type'], name='idx_catalog_type')],
                'unique_together': {('catalog_type', 'name')},
            },
        ),
    ]
