# Generated by Django 5.2.1 on 2026-05-15 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0002_add_catalog_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogvalue',
            name='catalog_type',
            field=models.CharField(max_length=100),
        ),
    ]
