# Generated by Django 5.2.1 on 2026-05-15 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_field_settings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fieldsettings',
            options={'ordering': ['entity', 'sort_order', 'field_name']},
        ),
        migrations.AddField(
            model_name='fieldsettings',
            name='label',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='fieldsettings',
            name='sort_order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fieldsettings',
            name='use_catalog',
            field=models.BooleanField(default=False),
        ),
    ]
