# Generated by Django 5.2.1 on 2026-05-21 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_label_sort_order_use_catalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldsettings',
            name='allow_filter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fieldsettings',
            name='allow_sort',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fieldsettings',
            name='filter_type',
            field=models.CharField(choices=[('none', 'Нет фильтра'), ('value', 'Список значений'), ('date', 'Диапазон дат'), ('number', 'Числовой диапазон'), ('text', 'Текстовый поиск')], default='none', max_length=20),
        ),
    ]
