# Generated by Django 5.2.1 on 2026-05-29 11:55

import django.db.models.deletion
from datetime import datetime, time, timedelta
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def _calculate_next_run(weekdays, run_time):
    weekday_numbers = {int(item) for item in weekdays.split(",") if item}
    now = timezone.now()
    local_now = timezone.localtime(now)
    current_tz = timezone.get_current_timezone()
    for offset in range(8):
        candidate_date = local_now.date() + timedelta(days=offset)
        if candidate_date.weekday() not in weekday_numbers:
            continue
        candidate = timezone.make_aware(datetime.combine(candidate_date, run_time), current_tz)
        if candidate > now:
            return candidate
    return None


def create_default_schedules(apps, schema_editor):
    BackupSchedule = apps.get_model("core", "BackupSchedule")
    defaults = [
        ("full", "6", time(2, 0)),
        ("incremental", "0,1,2,3,4,5", time(2, 0)),
    ]
    for backup_type, weekdays, run_time in defaults:
        BackupSchedule.objects.update_or_create(
            backup_type=backup_type,
            defaults={
                "enabled": True,
                "weekdays": weekdays,
                "run_time": run_time,
                "next_run_at": _calculate_next_run(weekdays, run_time),
            },
        )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_add_system_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='backuprun',
            name='source',
            field=models.CharField(choices=[('ui', 'UI'), ('scheduler', 'Scheduler'), ('script', 'Script'), ('restore', 'Restore')], default='ui', max_length=20),
        ),
        migrations.CreateModel(
            name='BackupSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backup_type', models.CharField(choices=[('full', 'Полный'), ('incremental', 'Инкрементальный')], max_length=20, unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('weekdays', models.CharField(help_text='Comma-separated weekday numbers, where 0 is Monday and 6 is Sunday.', max_length=20)),
                ('run_time', models.TimeField()),
                ('next_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_for_schedules', to='core.backuprun')),
            ],
            options={
                'db_table': 'backup_schedules',
                'ordering': ['backup_type'],
            },
        ),
        migrations.AddField(
            model_name='backuprun',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backup_runs', to='core.backupschedule'),
        ),
        migrations.AddIndex(
            model_name='backuprun',
            index=models.Index(fields=['source'], name='idx_backup_source'),
        ),
        migrations.RunPython(create_default_schedules, noop_reverse),
    ]
