# Generated by Django 5.2.1 on 2026-06-02 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_backuprun_source_backupschedule_backuprun_schedule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemstate',
            name='uploads_size_bytes',
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='systemstate',
            name='uploads_size_calculated_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
