# Generated by Django 5.2.1 on 2026-05-08 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RailShipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('departure_date', models.DateField()),
                ('wagon_number', models.CharField(max_length=50)),
                ('document_number', models.CharField(blank=True, default='', max_length=100)),
                ('cargo', models.CharField(max_length=255)),
                ('origin_region', models.CharField(blank=True, default='', max_length=255)),
                ('origin_station', models.CharField(blank=True, default='', max_length=255)),
                ('sender', models.CharField(blank=True, default='', max_length=255)),
                ('destination_region', models.CharField(blank=True, default='', max_length=255)),
                ('destination_station', models.CharField(blank=True, default='', max_length=255)),
                ('receiver', models.CharField(max_length=255)),
                ('volume', models.DecimalField(decimal_places=3, max_digits=12)),
                ('comment', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ЖД-отгрузка',
                'verbose_name_plural': 'ЖД-отгрузки',
                'db_table': 'rail_shipments',
                'ordering': ['-departure_date'],
                'indexes': [models.Index(fields=['departure_date'], name='idx_rail_date'), models.Index(fields=['wagon_number'], name='idx_rail_wagon'), models.Index(fields=['document_number'], name='idx_rail_document'), models.Index(fields=['receiver'], name='idx_rail_receiver'), models.Index(fields=['destination_station'], name='idx_rail_dest_station')],
            },
        ),
    ]
