# Generated by Django 5.2.1 on 2026-05-08 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipments_rail', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='railshipment',
            options={'ordering': ['-departure_date'], 'permissions': [('upload_documents', 'Загружать документы'), ('export_excel', 'Экспортировать в Excel')], 'verbose_name': 'ЖД-отгрузка', 'verbose_name_plural': 'ЖД-отгрузки'},
        ),
    ]
