# Generated by Django 5.2.1 on 2026-05-30 20:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments_rail', '0002_add_custom_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='railshipment',
            index=models.Index(fields=['departure_date', 'destination_station'], name='idx_rail_date_dest_station'),
        ),
        migrations.AddIndex(
            model_name='railshipment',
            index=models.Index(fields=['cargo', 'departure_date'], name='idx_rail_cargo_date'),
        ),
    ]
