# Generated by Django 5.2.15 on 2026-06-13 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipments_rail', '0005_alter_railshipment_volume'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='railshipment',
            options={'ordering': ['-departure_date'], 'permissions': [('export_excel', 'Экспортировать в Excel')], 'verbose_name': 'ЖД-отгрузка', 'verbose_name_plural': 'ЖД-отгрузки'},
        ),
    ]
