# Generated by Django 5.2.1 on 2026-05-08 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoShipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('shipment_date', models.DateField()),
                ('source_month_text', models.CharField(blank=True, default='', max_length=50)),
                ('source_day_number', models.IntegerField(blank=True, null=True)),
                ('customer_object', models.CharField(max_length=255)),
                ('sub_object', models.CharField(blank=True, default='', max_length=255)),
                ('vehicle_number', models.CharField(blank=True, default='', max_length=50)),
                ('driver_name', models.CharField(blank=True, default='', max_length=255)),
                ('ttn_number', models.CharField(blank=True, default='', max_length=100)),
                ('coal_grade', models.CharField(max_length=100)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('base_code', models.CharField(blank=True, default='', max_length=50)),
                ('upd_number', models.CharField(blank=True, default='', max_length=100)),
                ('carrier', models.CharField(blank=True, default='', max_length=255)),
                ('balance_note', models.CharField(blank=True, default='', max_length=255)),
                ('comment', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Автоотгрузка',
                'verbose_name_plural': 'Автоотгрузки',
                'db_table': 'auto_shipments',
                'ordering': ['-shipment_date'],
                'indexes': [models.Index(fields=['shipment_date'], name='idx_auto_date'), models.Index(fields=['ttn_number'], name='idx_auto_ttn'), models.Index(fields=['customer_object'], name='idx_auto_object'), models.Index(fields=['vehicle_number'], name='idx_auto_vehicle'), models.Index(fields=['coal_grade'], name='idx_auto_coal_grade')],
            },
        ),
    ]
