# Generated by Django 5.2.1 on 2026-05-30 20:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments_auto', '0002_add_custom_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='autoshipment',
            index=models.Index(fields=['coal_grade', 'shipment_date'], name='idx_auto_coal_grade_date'),
        ),
        migrations.AddIndex(
            model_name='autoshipment',
            index=models.Index(fields=['customer_object', 'shipment_date'], name='idx_auto_object_date'),
        ),
    ]
