# Generated by Django 5.2.1 on 2026-06-08 00:19

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments_auto', '0004_add_duplicate_check_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoshipment',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))]),
        ),
    ]
