# Generated by Django 5.2.15 on 2026-06-13 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipments_auto', '0005_alter_autoshipment_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autoshipment',
            options={'ordering': ['-shipment_date'], 'permissions': [('export_excel', 'Экспортировать в Excel')], 'verbose_name': 'Автоотгрузка', 'verbose_name_plural': 'Автоотгрузки'},
        ),
    ]
