GROUP_VIEWER = "viewer"
GROUP_EXCEL = "excel"
GROUP_OPERATOR = "operator"
GROUP_DOCUMENTS = "documents"
GROUP_ADMIN = "admin"

GROUP_DESCRIPTIONS = {
    GROUP_VIEWER: "Просмотр авто/ЖД отгрузок и документов без экспорта и изменений.",
    GROUP_EXCEL: "Просмотр авто/ЖД отгрузок и экспорт в Excel без изменения данных.",
    GROUP_OPERATOR: "Создание, изменение и soft delete авто/ЖД отгрузок без Excel-экспорта.",
    GROUP_DOCUMENTS: "Просмотр отгрузок, загрузка, изменение и удаление документов без изменения отгрузок.",
    GROUP_ADMIN: "Полный доступ, включая пользователей, справочники, настройки, аудит, импорт, документы и Excel.",
}

GROUPS = {
    GROUP_VIEWER: [
        "shipments_auto.view_autoshipment",
        "shipments_rail.view_railshipment",
        "documents.view_shipmentdocument",
    ],
    GROUP_EXCEL: [
        "shipments_auto.view_autoshipment",
        "shipments_auto.export_excel",
        "shipments_rail.view_railshipment",
        "shipments_rail.export_excel",
        "documents.view_shipmentdocument",
    ],
    GROUP_OPERATOR: [
        "shipments_auto.view_autoshipment",
        "shipments_auto.add_autoshipment",
        "shipments_auto.change_autoshipment",
        "shipments_auto.delete_autoshipment",
        "shipments_rail.view_railshipment",
        "shipments_rail.add_railshipment",
        "shipments_rail.change_railshipment",
        "shipments_rail.delete_railshipment",
        "documents.view_shipmentdocument",
    ],
    GROUP_DOCUMENTS: [
        "shipments_auto.view_autoshipment",
        "shipments_rail.view_railshipment",
        "documents.view_shipmentdocument",
        "documents.add_shipmentdocument",
        "documents.change_shipmentdocument",
        "documents.delete_shipmentdocument",
        "documents.upload_autoshipment_documents",
        "documents.upload_railshipment_documents",
        "documents.change_autoshipment_documents",
        "documents.change_railshipment_documents",
        "documents.delete_autoshipment_documents",
        "documents.delete_railshipment_documents",
    ],
    GROUP_ADMIN: [
        "shipments_auto.view_autoshipment",
        "shipments_auto.add_autoshipment",
        "shipments_auto.change_autoshipment",
        "shipments_auto.delete_autoshipment",
        "shipments_auto.export_excel",
        "shipments_rail.view_railshipment",
        "shipments_rail.add_railshipment",
        "shipments_rail.change_railshipment",
        "shipments_rail.delete_railshipment",
        "shipments_rail.export_excel",
        "documents.view_shipmentdocument",
        "documents.add_shipmentdocument",
        "documents.change_shipmentdocument",
        "documents.delete_shipmentdocument",
        "documents.upload_autoshipment_documents",
        "documents.upload_railshipment_documents",
        "documents.change_autoshipment_documents",
        "documents.change_railshipment_documents",
        "documents.delete_autoshipment_documents",
        "documents.delete_railshipment_documents",
        "accounts.view_user",
        "accounts.add_user",
        "accounts.change_user",
        "accounts.delete_user",
        "audit.view_auditlog",
        "imports.view_importlog",
        "imports.import_shipments",
        "catalogs.view_catalogvalue",
        "catalogs.add_catalogvalue",
        "catalogs.change_catalogvalue",
        "catalogs.delete_catalogvalue",
        "core.view_fieldsettings",
        "core.change_fieldsettings",
        "core.view_system_status",
        "core.change_system_mode",
        "core.recover_system_operations",
        "core.run_backup",
        "core.run_restore",
    ],
}
