# Generated by Django 5.2.1 on 2026-05-08 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_type', models.CharField(choices=[('auto', 'Авто'), ('rail', 'ЖД')], max_length=10)),
                ('shipment_id', models.BigIntegerField()),
                ('document_type', models.CharField(choices=[('ttn', 'ТТН'), ('upd', 'УПД'), ('invoice', 'Накладная'), ('photo', 'Фото'), ('scan', 'Скан'), ('other', 'Прочее')], default='other', max_length=50)),
                ('original_file_name', models.CharField(max_length=255)),
                ('stored_file_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=500)),
                ('mime_type', models.CharField(blank=True, default='', max_length=100)),
                ('file_size', models.BigIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
                'db_table': 'shipment_documents',
                'indexes': [models.Index(fields=['shipment_type', 'shipment_id'], name='idx_docs_shipment'), models.Index(fields=['uploaded_at'], name='idx_docs_uploaded_at')],
            },
        ),
    ]
