# Generated by Django 5.2.1 on 2026-05-19 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shipmentdocument',
            options={'permissions': [('upload_autoshipment_documents', 'Может прикреплять документы к автоотгрузкам'), ('upload_railshipment_documents', 'Может прикреплять документы к ЖД-отгрузкам')], 'verbose_name': 'Документ', 'verbose_name_plural': 'Документы'},
        ),
    ]
