# Generated by Django 5.2.1 on 2026-05-31 16:28

from django.db import migrations

NEW_CODENAMES = [
    "change_autoshipment_documents",
    "change_railshipment_documents",
    "delete_autoshipment_documents",
    "delete_railshipment_documents",
]


def add_perms_to_documents_group(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")
    try:
        group = Group.objects.get(name="documents")
    except Group.DoesNotExist:
        return
    for codename in NEW_CODENAMES:
        try:
            perm = Permission.objects.get(codename=codename, content_type__app_label="documents")
            group.permissions.add(perm)
        except Permission.DoesNotExist:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_add_upload_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shipmentdocument',
            options={'permissions': [('upload_autoshipment_documents', 'Может прикреплять документы к автоотгрузкам'), ('upload_railshipment_documents', 'Может прикреплять документы к ЖД-отгрузкам'), ('change_autoshipment_documents', 'Может изменять документы автоотгрузок'), ('change_railshipment_documents', 'Может изменять документы ЖД-отгрузок'), ('delete_autoshipment_documents', 'Может удалять документы автоотгрузок'), ('delete_railshipment_documents', 'Может удалять документы ЖД-отгрузок')], 'verbose_name': 'Документ', 'verbose_name_plural': 'Документы'},
        ),
        migrations.RunPython(add_perms_to_documents_group, migrations.RunPython.noop),
    ]
