# Generated by Django 5.2.1 on 2026-05-29 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0002_add_import_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='importlog',
            name='skipped_rows',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='importlog',
            name='updated_rows',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ImportRowResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_num', models.IntegerField()),
                ('status', models.CharField(choices=[('created', 'Создано'), ('updated', 'Обновлено'), ('skipped', 'Пропущено'), ('duplicate', 'Дубль'), ('error', 'Ошибка')], max_length=20)),
                ('messages', models.JSONField(blank=True, default=list)),
                ('source_data', models.JSONField(blank=True, default=dict)),
                ('created_object_id', models.BigIntegerField(blank=True, null=True)),
                ('created_object_label', models.CharField(blank=True, default='', max_length=255)),
                ('import_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='row_results', to='imports.importlog')),
            ],
            options={
                'verbose_name': 'Результат строки импорта',
                'verbose_name_plural': 'Результаты строк импорта',
                'db_table': 'import_row_results',
                'ordering': ['row_num'],
                'indexes': [models.Index(fields=['import_log', 'status'], name='idx_import_row_log_status')],
            },
        ),
    ]
